Heading styles
tulibraries/Press-6 pull request #149
Opened 2021-08-02 21:44 UTC by cdoyle-temple

Update gold color and admin edit links on page titles.

2021-08-02 21:45 UTC, cdoyle-temple commented
unrelated commits

2021-08-02 22:12 UTC, cdoyle-temple commented
Re-opening. The series work was already merged so should not effect anything.

2021-08-03 13:46 UTC, nomadicoder approved these changes

2021-08-03 13:47 UTC, nomadicoder requested changes
@cdoyle-temple Unable to rebase and merge.  Would you please address.

2021-08-03 13:55 UTC, nomadicoder approved these changes

2021-08-03 14:08 UTC, merged